openapi: 3.0.0
info:
  version: 1.0.0
  title: downloop api

paths:
  /users:
    get:
      responses:
        "200":
          description: get users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserList"

    post: 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: user post successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"

  /sessions:
    get:
      description: Returns a list of user sessions
      responses:
        "200":
          description: session list successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SessionList"
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Session"
      responses:
        "200":
          description: session post successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Session"
  
  /session/{id}:
    get:
      summary: set a session by id
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
      responses:
        "200":
          description: session post successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Session"
    delete:
      summary: delete a session by id
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
      responses:
        "204":
          description: deleted

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          x-oapi-codegen-extra-tags:
            db: id
        username:
          type: string
          x-oapi-codegen-extra-tags:
            db: username
    UserList:
      type: array
      items:
        $ref: "#/components/schemas/User"

    Session:
      type: object
      properties:
        id:
          type: string
          format: uuid
          x-oapi-codegen-extra-tags:
            db: id
        user_id:
          type: string
          format: uuid
          x-oapi-codegen-extra-tags:
            db: user_id 
        start_time:
          type: string
          format: date-time
          x-oapi-codegen-extra-tags:
            db: start_time
        end_time:
          type: string
          format: date-time
          x-oapi-codegen-extra-tags:
            db: end_time
      required:
      - start_time
    SessionList:
      type: array
      items:
        $ref: "#/components/schemas/Session"
