openapi: 3.0.0
info:
  version: 1.0.0
  title: downloop api

paths:
  /users:
    get:
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
        - name: offset
          in: query
          schema:
            type: integer

      responses:
        "200":
          description: users successfully listed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponseList"
        default:
          description: error creating user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserPost"
      responses:
        "201":
          description: user creation successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        default:
          description: error creating user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /sessions:
    get:
      description: Returns a list of user sessions
      responses:
        "200":
          description: session list successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SessionResponseList"
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SessionPost"
      responses:
        "201":
          description: session post successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SessionResponse"

  /session/{id}:
    get:
      summary: set a session by id
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
      responses:
        "200":
          description: session post successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SessionResponse"
    delete:
      summary: delete a session by id
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
      responses:
        "204":
          description: deleted

components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
      required:
        - code
        - message

    UserPost:
      type: object
      properties:
        username:
          type: string
      required:
        - username

    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
      required:
        - id
        - username

    UserResponse:
      type: object
      properties:
        data:
          $ref: "#/components/schemas/User"
      required:
        - data

    UserResponseList:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/User"
      required:
        - data

    SessionPost:
      type: object
      properties:
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
      required:
        - start_time

    Session:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
      required:
        - id
        #- user_id
        - start_time

    SessionResponse:
      type: object
      properties:
        data:
          $ref: "#/components/schemas/Session"
      required:
        - data

    SessionResponseList:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/Session"
      required:
        - data
